#!/usr/bin/env python3
"""Regenerate ``docs/issues.md`` from this repo's GitHub issues.

GitHub is the source of truth. This is run by ``.github/workflows/sync-issues.yaml`` on
issue events, and can also be run locally (requires ``gh`` to be authenticated). Issue
bodies are not mirrored — only number, title, state, labels, and the sub-issue parent.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "docs" / "issues.md"


def gh(*args: str) -> str:
    """Run a ``gh`` command and return stdout."""
    return subprocess.run(["gh", *args], capture_output=True, text=True, check=True).stdout


def repo_slug() -> str:
    """``OWNER/REPO`` from the Actions env, falling back to ``gh`` for local runs."""
    slug = os.environ.get("GITHUB_REPOSITORY")
    if slug:
        return slug
    return gh("repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner").strip()


def esc(value: str) -> str:
    """Escape table-breaking pipes and trim surrounding whitespace."""
    return value.replace("|", "\\|").strip()


def main() -> None:
    repo = repo_slug()
    issues = json.loads(
        gh(
            "issue",
            "list",
            "--repo",
            repo,
            "--state",
            "all",
            "--limit",
            "500",
            "--json",
            "number,title,state,labels",
        )
    )

    # Build a child-number -> parent-number map from the sub-issue graph.
    parent_of: dict[int, int] = {}
    for issue in issues:
        number = issue["number"]
        try:
            children = json.loads(
                gh("api", f"repos/{repo}/issues/{number}/sub_issues", "--jq", "[.[].number]")
            )
        except subprocess.CalledProcessError:
            children = []  # issue has no sub-issues (endpoint 404s)
        for child in children:
            parent_of[child] = number

    rows = []
    for issue in sorted(issues, key=lambda i: i["number"]):
        number = issue["number"]
        title = esc(issue["title"])
        state = issue["state"].lower()
        labels = esc(", ".join(sorted(label["name"] for label in issue["labels"])))
        parent = parent_of.get(number, "")
        rows.append(f"| {number} | {title} | {state} | {labels} | {parent} |")

    preamble = (
        "# Issues\n"
        "\n"
        "> Auto-generated — do not edit by hand. This table mirrors the GitHub issues for\n"
        f"> [`{repo}`](https://github.com/{repo}/issues) and is regenerated by the `sync-issues`\n"
        "> workflow (`.github/workflows/sync-issues.yaml`) on every issue event. GitHub is the\n"
        "> source of truth — manage issues there, not here. Issue bodies are not mirrored.\n"
        "\n"
        "| #   | Title | State | Labels | Parent |\n"
        "| --- | ----- | ----- | ------ | ------ |\n"
    )
    OUT.write_text(preamble + "\n".join(rows) + "\n")
    print(f"Wrote {len(rows)} issues to {OUT}")


if __name__ == "__main__":
    main()
